#pragma once

#include <string_view>

namespace UwpImGuiFrontend::Sample
{
// Placements follow settings_dialog.ui and settings_dialog.cpp bindings.
// The embedding API remains the authority for values, ranges and supported choices.
struct DesktopSettingPlacement { std::string_view path, page, section; unsigned column = 0; };
inline constexpr DesktopSettingPlacement desktopSettings[] = {
	{"Core/PPU Decoder", "CPU", "PPU Decoder"},
	{"Core/SPU Decoder", "CPU", "SPU Decoder"},
	{"Core/SPU XFloat Accuracy", "CPU", "SPU XFloat Accuracy", 0},
	{"Core/SPU Block Size", "CPU", "SPU Block Size", 0},
	{"Core/Max CPU Preempt Count", "CPU", "Max Power Saving CPU-preemptions", 0},
	{"Core/Preferred SPU Threads", "CPU", "Preferred SPU Threads", 1},
	{"Core/Thread Scheduler Mode", "CPU", "Thread Scheduler", 1},
	{"Video/Renderer", "GPU", "Renderer", 0},
	{"Video/Vulkan/Adapter", "GPU", "Graphics Device", 0},
	{"Video/Aspect ratio", "GPU", "Aspect Ratio", 0},
	{"Video/Frame limit", "GPU", "Framelimit", 0},
	{"Video/Anisotropic Filter Override", "GPU", "Anisotropic Filter", 0},
	{"Video/MSAA", "GPU", "Anti-Aliasing (MSAA)", 0},
	{"Video/Shader Precision", "GPU", "Shader Quality", 0},
	{"Video/VSync Mode", "GPU", "Vsync", 0},
	{"Video/3D Display Enabled", "GPU", "3D", 0},
	{"Video/3D Display Mode", "GPU", "3D", 0},
	{"Video/Screen size in inches", "GPU", "Screen Size (Inch)", 0},
	{"Video/Resolution", "GPU", "Default Resolution", 0},
	{"Video/Resolution Scale", "GPU", "Resolution Scale (Disable Strict Mode)", 0},
	{"Video/Minimum Scalable Dimension", "GPU", "Resolution Scale Threshold", 0},
	{"Video/FidelityFX CAS Sharpening Intensity", "GPU", "Output Scaling", 0},
	{"Video/Output Scaling Mode", "GPU", "Output Scaling", 0},
	{"Video/Vulkan/Asynchronous Texture Streaming", "GPU", "Additional Settings", 1},
	{"Input/Output/Background input enabled", "I/O", "Additional Settings", 0},
	{"Input/Output/Keep pads connected", "I/O", "Additional Settings", 0},
	{"Input/Output/Lock overlay input to player one", "I/O", "Additional Settings", 0},
	{"Input/Output/Mouse-based gyro enabled", "I/O", "Additional Settings", 0},
	{"Input/Output/Show move cursor", "I/O", "Additional Settings", 0},
	{"Video/Multithreaded RSX", "GPU", "Additional Settings", 1},
	{"Video/Stretch To Display Area", "GPU", "Additional Settings", 1},
	{"Video/Strict Rendering Mode", "GPU", "Additional Settings", 1},
	{"Video/Write Color Buffers", "GPU", "Additional Settings", 1},
	{"Audio/Renderer", "Audio", "Audio Out", 0},
	{"Audio/Audio Device", "Audio", "Audio Device", 0},
	{"Audio/Audio Format", "Audio", "Audio Format", 0},
	{"Audio/Convert to 16 bit", "Audio", "Audio Settings", 0},
	{"Audio/Dump to file", "Audio", "Audio Settings", 0},
	{"Audio/Audio Channel Layout", "Audio", "Audio Output Format", 0},
	{"Audio/Audio Provider", "Audio", "Audio Provider", 0},
	{"Audio/RSXAudio Avport", "Audio", "RSXAudio Avport", 0},
	{"Audio/Music Handler", "Audio", "Music Handler", 0},
	{"Audio/Master Volume", "Audio", "Volume", 0},
	{"Audio/Desired Audio Buffer Duration", "Audio", "Buffering", 1},
	{"Audio/Enable Buffering", "Audio", "Buffering", 1},
	{"Audio/Enable Time Stretching", "Audio", "Buffering", 1},
	{"Audio/Time Stretching Threshold", "Audio", "Buffering", 1},
	{"Audio/Microphone Type", "Audio", "Microphone Settings", 0},
	{"Input/Output/GHLtar emulated controller", "I/O", "Guitar Hero Live Emulated Guitar", 0},
	{"Input/Output/Move", "I/O", "Move Handler", 0},
	{"Input/Output/Turntable emulated controller", "I/O", "DJ Hero Emulated Turntable", 0},
	{"Input/Output/Mouse", "I/O", "Mouse Handler", 0},
	{"Input/Output/Buzz emulated controller", "I/O", "Buzz! Emulated Controller", 0},
	{"Input/Output/Keyboard", "I/O", "Keyboard Handler", 0},
	{"Input/Output/Pad handler mode", "I/O", "Pad Handler Mode", 0},
	{"Input/Output/Camera type", "I/O", "Camera Input", 0},
	{"Input/Output/Camera flip", "I/O", "Camera Flip", 0},
	{"Input/Output/Camera ID", "I/O", "Camera", 0},
	{"Input/Output/Camera", "I/O", "Camera Handler", 0},
	{"System/Language", "System", "Console Language", 0},
	{"System/License Area", "System", "Console Region", 0},
	{"VFS/Disk cache maximum size (MB)", "System", "Disk Cache", 0},
	{"VFS/Limit disk cache size", "System", "Disk Cache", 0},
	{"System/Keyboard Type", "System", "Keyboard Type", 0},
	{"System/Date Format", "System", "Date Format", 0},
	{"System/Time Format", "System", "Time Format", 0},
	{"System/Console time offset (s)", "System", "Console Time", 0},
	{"VFS/Empty /dev_hdd0/tmp/", "System", "Homebrew", 1},
	{"VFS/Enable /host_root/", "System", "Homebrew", 1},
	{"Net/Derive MAC from PSID", "Network", "Network Configuration", 0},
	{"Net/UPNP Enabled", "Network", "Network Configuration", 0},
	{"Net/Internet enabled", "Network", "Network Status", 0},
	{"Net/DNS address", "Network", "DNS", 0},
	{"Net/IP swap list", "Network", "IP/Hosts switches", 0},
	{"Net/Bind address", "Network", "Bind address", 0},
	{"Net/Clans Enabled", "Network", "PSN Configuration", 0},
	{"Net/PSN status", "Network", "PSN Status", 0},
	{"Core/Accurate RSX reservation access", "Advanced", "Core", 0},
	{"Core/Accurate SPU DMA", "Advanced", "Core", 0},
	{"Core/Accurate SPU Reservations", "Advanced", "Core", 0},
	{"Core/Debug Console Mode", "Advanced", "Core", 0},
	{"Core/Disable SPU GETLLAR Spin Optimization", "Advanced", "Core", 0},
	{"Core/Enable Performance Report", "Debug", "Core", 0},
	{"Core/Hook static functions", "Debug", "Core", 0},
	{"Core/LLVM Precompilation", "Advanced", "Core", 0},
	{"Core/MFC Debug", "Debug", "Core", 0},
	{"Core/PPU Debug", "Debug", "Core", 0},
	{"Core/PPU Reservation Priority Over SPUs", "Advanced", "Core", 0},
	{"Core/Set DAZ and FTZ", "Debug", "Core", 0},
	{"Core/SPU Debug", "Debug", "Core", 0},
	{"Core/SPU loop detection", "Advanced", "Core", 0},
	{"Core/SPU Profiler", "Debug", "Core", 0},
	{"Core/SPU Reservation Busy Waiting Enabled", "Debug", "Core", 0},
	{"Miscellaneous/Automatically start games after boot", "Debug", "Core", 0},
	{"Miscellaneous/Silence All Logs", "Advanced", "Core", 0},
	{"VFS/Emulate HDD Read Speed", "Advanced", "Core", 0},
	{"Core/Sleep Timers Accuracy", "Advanced", "Sleep Timers Accuracy", 0},
	{"Core/Max SPURS Threads", "Advanced", "Maximum Number of SPURS Threads", 0},
	{"Core/Clocks scale", "Advanced", "Clocks Scale", 0},
	{"Core/Libraries Control", "Advanced", "Firmware Libraries", 1},
	{"Video/Vulkan/Use Re-BAR for GPU uploads", "Advanced", "GPU", 2},
	{"Video/Allow Host GPU Labels", "Advanced", "GPU", 2},
	{"Video/Debug output", "Debug", "GPU", 0},
	{"Video/Debug overlay", "Debug", "GPU", 0},
	{"Video/Disable Asynchronous Memory Manager", "Debug", "GPU", 0},
	{"Video/Disable Blit Engine Upscaling", "Advanced", "GPU", 2},
	{"Video/Disable FIFO Reordering", "Debug", "GPU", 0},
	{"Video/Disable Hardware Blending", "Debug", "GPU", 0},
	{"Video/Disable Hardware ColorSpace Remapping", "Debug", "GPU", 0},
	{"Video/Disable MSL Fast Math", "Advanced", "GPU", 2},
	{"Video/Disable On-Disk Shader Cache", "Debug", "GPU", 0},
	{"Video/Disable Vertex Cache", "Advanced", "GPU", 2},
	{"Video/Disable Video Output", "Debug", "GPU", 0},
	{"Video/Disable Vulkan Memory Allocator", "Debug", "GPU", 0},
	{"Video/Disable ZCull Occlusion Queries", "Debug", "GPU", 0},
	{"Video/Emulate Special Depth Comparison", "Advanced", "GPU", 2},
	{"Video/Force CPU Blit", "Debug", "GPU", 0},
	{"Video/Force Hardware MSAA Resolve", "Advanced", "GPU", 2},
	{"Video/Force High Precision Z buffer", "Debug", "GPU", 0},
	{"Video/Handle RSX Memory Tiling", "Advanced", "GPU", 2},
	{"Video/Log shader programs", "Debug", "GPU", 0},
	{"Video/Read Color Buffers", "Advanced", "GPU", 2},
	{"Video/Read Depth Buffer", "Advanced", "GPU", 2},
	{"Video/Renderdoc Compatibility Mode", "Debug", "GPU", 0},
	{"Video/Strict Texture Flushing", "Debug", "GPU", 0},
	{"Video/Use GPU texture scaling", "Debug", "GPU", 0},
	{"Video/Write Depth Buffer", "Advanced", "GPU", 2},
	{"Core/RSX FIFO Fetch Accuracy", "Advanced", "RSX FIFO Accuracy", 2},
	{"Video/Vulkan/Exclusive Fullscreen Mode", "Advanced", "Exclusive Fullscreen Mode", 2},
	{"Video/Driver Wake-Up Delay", "Advanced", "Driver Wake-Up Delay", 2},
	{"Video/Vblank Rate", "Advanced", "VBlank Frequency", 2},
	{"Miscellaneous/Enable GameMode", "Emulator", "Emulator Settings", 0},
	{"Miscellaneous/Exit RPCS3 when process finishes", "Emulator", "Emulator Settings", 0},
	{"Miscellaneous/Pause Emulation During Home Menu", "Emulator", "Emulator Settings", 0},
	{"Miscellaneous/Pause emulation on RPCS3 focus loss", "Emulator", "Emulator Settings", 0},
	{"Miscellaneous/Prevent display sleep while running games", "Emulator", "Emulator Settings", 0},
	{"Miscellaneous/Start Big Picture Mode on boot", "Emulator", "Emulator Settings", 0},
	{"Miscellaneous/Start games in fullscreen mode", "Emulator", "Emulator Settings", 0},
	{"Miscellaneous/Use native user interface", "Emulator", "Emulator Settings", 0},
	{"Miscellaneous/Use recursive scan", "Emulator", "Emulator Settings", 0},
	{"Miscellaneous/Play music during boot sequence", "Emulator", "Overlay Settings", 0},
	{"Miscellaneous/Show analog limiter toggle hint", "Emulator", "Overlay Settings", 0},
	{"Miscellaneous/Show autosave/autoload hint", "Emulator", "Overlay Settings", 0},
	{"Miscellaneous/Show capture hints", "Emulator", "Overlay Settings", 0},
	{"Miscellaneous/Show fatal error hints", "Emulator", "Overlay Settings", 0},
	{"Miscellaneous/Show mouse and keyboard toggle hint", "Emulator", "Overlay Settings", 0},
	{"Miscellaneous/Show PPU compilation hint", "Emulator", "Overlay Settings", 0},
	{"Miscellaneous/Show pressure intensity toggle hint", "Emulator", "Overlay Settings", 0},
	{"Miscellaneous/Show RPCN popups", "Emulator", "Overlay Settings", 0},
	{"Miscellaneous/Show shader compilation hint", "Emulator", "Overlay Settings", 0},
	{"Miscellaneous/Show trophy popups", "Emulator", "Overlay Settings", 0},
	{"Video/Record With Overlays", "Emulator", "Overlay Settings", 0},
	{"Core/Max LLVM Compile Threads", "Emulator", "Max LLVM Compile Threads", 0},
	{"Video/Shader Compiler Threads", "Emulator", "Max Shader Compile Threads", 0},
	{"Video/Shader Loading Dialog/Allow custom background", "Emulator", "Shader Loading Screen", 0},
	{"Video/Shader Loading Dialog/Blur effect strength", "Emulator", "Shader Loading Screen", 0},
	{"Video/Shader Loading Dialog/Darkening effect strength", "Emulator", "Shader Loading Screen", 0},
	{"Video/Performance Overlay/Center Horizontally", "Emulator", "Performance Overlay", 1},
	{"Video/Performance Overlay/Center Vertically", "Emulator", "Performance Overlay", 1},
	{"Video/Performance Overlay/Detail level", "Emulator", "Performance Overlay", 1},
	{"Video/Performance Overlay/Enable Framerate Graph", "Emulator", "Performance Overlay", 1},
	{"Video/Performance Overlay/Enable Frametime Graph", "Emulator", "Performance Overlay", 1},
	{"Video/Performance Overlay/Enabled", "Emulator", "Performance Overlay", 1},
	{"Video/Performance Overlay/Font size (px)", "Emulator", "Performance Overlay", 1},
	{"Video/Performance Overlay/Framerate datapoints", "Emulator", "Performance Overlay", 1},
	{"Video/Performance Overlay/Frametime datapoints", "Emulator", "Performance Overlay", 1},
	{"Video/Performance Overlay/Horizontal Margin (%)", "Emulator", "Performance Overlay", 1},
	{"Video/Performance Overlay/Metrics update interval (ms)", "Emulator", "Performance Overlay", 1},
	{"Video/Performance Overlay/Opacity (%)", "Emulator", "Performance Overlay", 1},
	{"Video/Performance Overlay/Position", "Emulator", "Performance Overlay", 1},
	{"Video/Performance Overlay/Use Window Space", "Emulator", "Performance Overlay", 1},
	{"Video/Performance Overlay/Vertical Margin (%)", "Emulator", "Performance Overlay", 1},
	{"Core/Accurate Cache Line Stores", "Debug", "CPU Accuracy", 0},
	{"Core/PPU Accurate Non-Java Mode", "Debug", "CPU Accuracy", 0},
	{"Core/PPU Accurate Vector NaN Values", "Debug", "CPU Accuracy", 0},
	{"Core/PPU Set FPCC Bits", "Debug", "CPU Accuracy", 0},
	{"Core/PPU Set Saturation Bit", "Debug", "CPU Accuracy", 0},
	{"Core/Accurate PPU 128-byte Reservation Op Max Length", "Debug", "Accurate PPU 128 Reservations", 0},
	{"Core/PPU Threads", "Debug", "PPU Thread Count", 0},
	{"Video/Texture LOD Bias Addend", "Debug", "LOD Bias Offset", 0},
	{"Video/Vulkan/Asynchronous Queue Scheduler", "Debug", "Vulkan Queue Scheduler", 0},
	{"Video/Framebuffer Aliasing Heuristic Bias", "Debug", "Framebuffer Aliasing Heuristic Bias", 0},
	{"Input/Output/IO Debug overlay", "Debug", "I/O", 0},
	{"Input/Output/Mouse Debug overlay", "Debug", "I/O", 0},
};
}

